name: deploy-gh-pages

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.13.8
          channel: "stable"

      - run: flutter config --enable-web
      - run: flutter channel beta
      - run: flutter create .
      - run: rm test/widget_test.dart
      - run: flutter pub get
      - run: flutter build web
      - run: flutter test

      - uses: actions/configure-pages@v3
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./build/web
      - uses: actions/upload-pages-artifact@v1
      - uses: actions/deploy-pages@v3
