name: deploy-gh-pages

on:
  push:
    branches: [ main ]

  # allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.13.8
          channel: "stable"

      # enable web
      # remove widget_test which is based on the default app
      # remove base href from index.html for gh-pages
      - name: Build with Flutter
        run: |
          flutter config --enable-web
          flutter channel beta
          flutter create .
          rm test/widget_test.dart
          cp assets/favicon.png web/favicon.png
          flutter pub get
          flutter test
          flutter build web --web-renderer canvaskit --release
          sed -i '/base href/d' ./build/web/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
